"""tabelas iniciais

Revision ID: a7efc8bb2bf5
Revises: 
Create Date: 2026-10-09 11:07:44.107233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7efc8bb2bf5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TECNICO', 'SOLICITANTE', name='user_role', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'TECNICO', 'SOLICITANTE')", name=op.f('ck_users_user_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANDAMENTO', 'RESOLVIDO', 'FECHADO', name='ticket_status', native_enum=False, create_constraint=False), server_default='ABERTO', nullable=False),
    sa.Column('priority', sa.Enum('CRITICA', 'ALTA', 'MEDIA', 'BAIXA', name='ticket_priority', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('CRITICA', 'ALTA', 'MEDIA', 'BAIXA')", name=op.f('ck_tickets_ticket_priority')),
    sa.CheckConstraint("status <> 'EM_ANDAMENTO' OR assigned_to_id IS NOT NULL", name=op.f('ck_tickets_in_progress_has_assignee')),
    sa.CheckConstraint("status <> 'FECHADO' OR closed_at IS NOT NULL", name=op.f('ck_tickets_closed_at_required')),
    sa.CheckConstraint("status IN ('ABERTO', 'EM_ANDAMENTO', 'RESOLVIDO', 'FECHADO')", name=op.f('ck_tickets_ticket_status')),
    sa.CheckConstraint("status NOT IN ('RESOLVIDO', 'FECHADO') OR resolved_at IS NOT NULL", name=op.f('ck_tickets_resolved_at_required')),
    sa.CheckConstraint("status NOT IN ('RESOLVIDO', 'FECHADO') OR solution IS NOT NULL", name=op.f('ck_tickets_solution_required')),
    sa.CheckConstraint('char_length(trim(title)) BETWEEN 3 AND 120', name=op.f('ck_tickets_title_length')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_tickets_assigned_to_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_tickets_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_tickets_requester_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index(op.f('ix_tickets_assigned_to_id'), 'tickets', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tickets_category_id'), 'tickets', ['category_id'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_requester_id'), 'tickets', ['requester_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(message)) > 0', name=op.f('ck_comments_message_not_empty')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_comments_ticket_id_tickets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_ticket_id'), 'comments', ['ticket_id'], unique=False)
    op.create_table('ticket_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CRIADO', 'EDITADO', 'STATUS_ALTERADO', 'ATRIBUIDO', 'PRIORIDADE_ALTERADA', 'CATEGORIA_ALTERADA', 'SOLUCAO_REGISTRADA', 'REABERTO', 'ARQUIVADO', name='history_action', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('CRIADO', 'EDITADO', 'STATUS_ALTERADO', 'ATRIBUIDO', 'PRIORIDADE_ALTERADA', 'CATEGORIA_ALTERADA', 'SOLUCAO_REGISTRADA', 'REABERTO', 'ARQUIVADO')", name=op.f('ck_ticket_history_history_action')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_history_ticket_id_tickets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ticket_history_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_history'))
    )
    op.create_index(op.f('ix_ticket_history_ticket_id_created_at'), 'ticket_history', ['ticket_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_history_ticket_id_created_at'), table_name='ticket_history')
    op.drop_table('ticket_history')
    op.drop_index(op.f('ix_comments_ticket_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_requester_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
